# Generated by Django 4.2.7 on 2023-11-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("additional_description", models.TextField()),
                ("additional_info", models.TextField()),
                ("price", models.IntegerField(default=0)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("ML", "ML"),
                            ("XL", "XL"),
                        ],
                        default="M",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("BLACK", "Black"),
                            ("WHITE", "White"),
                            ("RED", "Red"),
                            ("BLUE", "Blue"),
                            ("GREEN", "Green"),
                        ],
                        default="RED",
                    ),
                ),
                ("images", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
