# Generated by Django 4.2.7 on 2023-11-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_remove_product_images_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.IntegerField(default=0),
        ),
    ]
