# Generated by Django 4.2.7 on 2023-11-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="star",
        ),
        migrations.AddField(
            model_name="product",
            name="star",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
