# Generated by Django 4.2.7 on 2023-11-12 01:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_remove_review_star_product_star"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size",
        ),
    ]
