# Generated by Django 4.2.7 on 2023-11-12 01:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_remove_product_color_remove_product_size"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
