# Generated by Django 4.2.7 on 2023-11-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_delete_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
