# Generated by Django 4.2.7 on 2023-11-12 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_alter_product_discount"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
        migrations.AlterModelTable(
            name="image",
            table="image",
        ),
        migrations.AlterModelTable(
            name="product",
            table="product",
        ),
    ]
