# Generated by Django 4.2.7 on 2023-11-12 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="review",
            table="review",
        ),
    ]
