# Generated by Django 4.2.7 on 2023-11-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_remove_order_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name="producttype",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
