# Generated by Django 4.2.7 on 2023-11-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_remove_order_quantity_order_total_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
