# Generated by Django 4.2.7 on 2023-11-12 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_order_is_paid"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="order",
            table="order",
        ),
        migrations.AlterModelTable(
            name="producttype",
            table="product_type",
        ),
    ]
